var baseUrl = 'http://wwwtest.sistemafiergs.org.br:8897/mapws/';
//var baseUrl = 'http://10.25.12.110:8894/mapws/';
//var baseUrlAuth = 'http://10.25.12.110:8894/authws/';
var baseUrlAuth = 'http://wwwtest.sistemafiergs.org.br:8890/authws/';
var itemUrl = baseUrl + 'item/';
var autenticarUrl = baseUrlAuth + 'autenticar/';
var logoffUrl =  baseUrlAuth + 'logoff/';
var perfilUsuarioUrl = baseUrl + 'perfilusuario/';
var versaoUrl = baseUrl + 'versao'
var sigla = 'MAP';
var versao = '1.0';